apiVersion: v1
name: unnecessary-ly-backend
version: 0.0.4
description: Java backend for an unnecessary brick breaker clone.
type: application
home: https://pojntfx.github.io/unnecessary.ly-backend-java/
sources:
  - git@github.com:pojntfx/unnecessary.ly-backend-java.git
maintainers:
  - name: Felix Pojtinger
    email: felix@pojtinger.com
    url: https://felix.pojtinger.com
appVersion: 0.0.4
dependencies:
  - name: postgresql
    version: 8.10.14
    repository: https://charts.bitnami.com/bitnami
  - name: nats
    version: 4.5.1
    repository: https://charts.bitnami.com/bitnami
